linters:
  enable:
    - errorlint
    - err113
    - exhaustruct
    - gocritic
    - gofmt
    - nilnil
    - nlreturn
    - wrapcheck
    - wsl
linters-settings:
  wrapcheck:
    ignorePackageGlobs:
      - github.com/couchbaselabs/gocbconnstr
      - crypto/x509
    ignoreInterfaceRegexps:
      - "analyticsRowReader"
      - "queryClient"
      - "clusterClient"

