name: Create Release

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'SHA of the commit to tag'
        required: true

permissions:
  packages: write
  actions: write
  contents: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
  tag:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - name: Tag version
        id: tag_version
        run: |
          version=`grep versionStr ${{ github.workspace }}/version.go | head -1 | awk '{print $3}' | cut -d "\\"" -f 2 | tr -d "\\n"`
          echo $version
          echo "VERSION=$version" >> "$GITHUB_OUTPUT"
      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ inputs.sha }}
          custom_tag: ${{ steps.tag_version.outputs.version }}
          default_bump: false
          create_annotated_tag: true
          tag_prefix: ""
